// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/moby/buildkit/frontend/gateway/client (interfaces: Client,Reference)
//
// Generated by this command:
//
//	mockgen -package cib_mock -destination mock/client.go github.com/moby/buildkit/frontend/gateway/client Client,Reference
//

// Package cib_mock is a generated GoMock package.
package cib_mock

import (
	context "context"
	reflect "reflect"

	llb "github.com/moby/buildkit/client/llb"
	sourceresolver "github.com/moby/buildkit/client/llb/sourceresolver"
	client "github.com/moby/buildkit/frontend/gateway/client"
	pb "github.com/moby/buildkit/solver/pb"
	digest "github.com/opencontainers/go-digest"
	types "github.com/tonistiigi/fsutil/types"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// BuildOpts mocks base method.
func (m *MockClient) BuildOpts() client.BuildOpts {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildOpts")
	ret0, _ := ret[0].(client.BuildOpts)
	return ret0
}

// BuildOpts indicates an expected call of BuildOpts.
func (mr *MockClientMockRecorder) BuildOpts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildOpts", reflect.TypeOf((*MockClient)(nil).BuildOpts))
}

// Inputs mocks base method.
func (m *MockClient) Inputs(ctx context.Context) (map[string]llb.State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inputs", ctx)
	ret0, _ := ret[0].(map[string]llb.State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inputs indicates an expected call of Inputs.
func (mr *MockClientMockRecorder) Inputs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inputs", reflect.TypeOf((*MockClient)(nil).Inputs), ctx)
}

// NewContainer mocks base method.
func (m *MockClient) NewContainer(ctx context.Context, req client.NewContainerRequest) (client.Container, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewContainer", ctx, req)
	ret0, _ := ret[0].(client.Container)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewContainer indicates an expected call of NewContainer.
func (mr *MockClientMockRecorder) NewContainer(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewContainer", reflect.TypeOf((*MockClient)(nil).NewContainer), ctx, req)
}

// ResolveImageConfig mocks base method.
func (m *MockClient) ResolveImageConfig(ctx context.Context, ref string, opt sourceresolver.Opt) (string, digest.Digest, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveImageConfig", ctx, ref, opt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(digest.Digest)
	ret2, _ := ret[2].([]byte)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ResolveImageConfig indicates an expected call of ResolveImageConfig.
func (mr *MockClientMockRecorder) ResolveImageConfig(ctx, ref, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveImageConfig", reflect.TypeOf((*MockClient)(nil).ResolveImageConfig), ctx, ref, opt)
}

// ResolveSourceMetadata mocks base method.
func (m *MockClient) ResolveSourceMetadata(ctx context.Context, op *pb.SourceOp, opt sourceresolver.Opt) (*sourceresolver.MetaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveSourceMetadata", ctx, op, opt)
	ret0, _ := ret[0].(*sourceresolver.MetaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveSourceMetadata indicates an expected call of ResolveSourceMetadata.
func (mr *MockClientMockRecorder) ResolveSourceMetadata(ctx, op, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveSourceMetadata", reflect.TypeOf((*MockClient)(nil).ResolveSourceMetadata), ctx, op, opt)
}

// Solve mocks base method.
func (m *MockClient) Solve(ctx context.Context, req client.SolveRequest) (*client.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Solve", ctx, req)
	ret0, _ := ret[0].(*client.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Solve indicates an expected call of Solve.
func (mr *MockClientMockRecorder) Solve(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Solve", reflect.TypeOf((*MockClient)(nil).Solve), ctx, req)
}

// Warn mocks base method.
func (m *MockClient) Warn(ctx context.Context, dgst digest.Digest, msg string, opts client.WarnOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Warn", ctx, dgst, msg, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Warn indicates an expected call of Warn.
func (mr *MockClientMockRecorder) Warn(ctx, dgst, msg, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockClient)(nil).Warn), ctx, dgst, msg, opts)
}

// MockReference is a mock of Reference interface.
type MockReference struct {
	ctrl     *gomock.Controller
	recorder *MockReferenceMockRecorder
	isgomock struct{}
}

// MockReferenceMockRecorder is the mock recorder for MockReference.
type MockReferenceMockRecorder struct {
	mock *MockReference
}

// NewMockReference creates a new mock instance.
func NewMockReference(ctrl *gomock.Controller) *MockReference {
	mock := &MockReference{ctrl: ctrl}
	mock.recorder = &MockReferenceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReference) EXPECT() *MockReferenceMockRecorder {
	return m.recorder
}

// Evaluate mocks base method.
func (m *MockReference) Evaluate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockReferenceMockRecorder) Evaluate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockReference)(nil).Evaluate), ctx)
}

// ReadDir mocks base method.
func (m *MockReference) ReadDir(ctx context.Context, req client.ReadDirRequest) ([]*types.Stat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", ctx, req)
	ret0, _ := ret[0].([]*types.Stat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockReferenceMockRecorder) ReadDir(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockReference)(nil).ReadDir), ctx, req)
}

// ReadFile mocks base method.
func (m *MockReference) ReadFile(ctx context.Context, req client.ReadRequest) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", ctx, req)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockReferenceMockRecorder) ReadFile(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockReference)(nil).ReadFile), ctx, req)
}

// StatFile mocks base method.
func (m *MockReference) StatFile(ctx context.Context, req client.StatRequest) (*types.Stat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatFile", ctx, req)
	ret0, _ := ret[0].(*types.Stat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatFile indicates an expected call of StatFile.
func (mr *MockReferenceMockRecorder) StatFile(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatFile", reflect.TypeOf((*MockReference)(nil).StatFile), ctx, req)
}

// ToState mocks base method.
func (m *MockReference) ToState() (llb.State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToState")
	ret0, _ := ret[0].(llb.State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToState indicates an expected call of ToState.
func (mr *MockReferenceMockRecorder) ToState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToState", reflect.TypeOf((*MockReference)(nil).ToState))
}
