name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.37
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: Install test runner
        run: curl -sSL "https://github.com/gotestyourself/gotestsum/releases/download/v1.6.2/gotestsum_1.6.2_linux_amd64.tar.gz" | sudo tar -xz -C /usr/local/bin gotestsum

      - name: Test
        run: gotestsum --junitfile unit-tests.xml -- -v -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: unit-tests.xml

      - name: Upload coverage
        uses: codecov/codecov-action@v1
